db2/config/routes.rb
Rails.application.routes.draw do
  resources :fund_data
  resources :funds
  resources :portfolios
  resources :managers
  resources :users

end

db2/app/models/fund.rb
class Fund < ActiveRecord::Base
	has_and_belongs_to_many :portfolios
	belongs_to :manager
	has_many :fund_data
end

db2/app/controllers/funds_controller.rb
class FundsController < ApplicationController
  before_action :set_fund, only: [:show, :edit, :update, :destroy]

  # GET /funds
  # GET /funds.json
  def index
    @funds = Fund.all
  end

  # GET /funds/1
  # GET /funds/1.json
  def show
  end

  # GET /funds/new
  def new
    @fund = Fund.new
  end

  # GET /funds/1/edit
  def edit
  end

  # POST /funds
  # POST /funds.json
  def create
    @fund = Fund.new(fund_params)

    respond_to do |format|
      if @fund.save
        format.html { redirect_to @fund, notice: 'Fund was successfully created.' }
        format.json { render :show, status: :created, location: @fund }
      else
        format.html { render :new }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funds/1
  # PATCH/PUT /funds/1.json
  def update
    respond_to do |format|
      if @fund.update(fund_params)
        format.html { redirect_to @fund, notice: 'Fund was successfully updated.' }
        format.json { render :show, status: :ok, location: @fund }
      else
        format.html { render :edit }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funds/1
  # DELETE /funds/1.json
  def destroy
    @fund.destroy
    respond_to do |format|
      format.html { redirect_to funds_url, notice: 'Fund was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fund
      @fund = Fund.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fund_params
      params.require(:fund).permit(:name, :shortName, :isinCode, :cnpj, :exclusive, :nqPeerGroupName, :niPeerGroupName, :cvmClass, :anbimaClass, :adminFee, :performanceFeeDescription, :isIgi, :isIgiExotic, :hasRestriction, :targetClientList, :minimumInvestmentAmount, :vehicleType, :redemptionPaymentPeriod, :redemptionConversionPeriod, :totalShareHolders, :manager_id)
    end
end

db2/app/helpers/funds_helper.rb
module FundsHelper
end

db2/app/views/funds/_form.html.erb
<%= form_for(@fund) do |f| %>
  <% if @fund.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fund.errors.count, "error") %> prohibited this fund from being saved:</h2>

      <ul>
      <% @fund.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :shortName %><br>
    <%= f.text_field :shortName %>
  </div>
  <div class="field">
    <%= f.label :isinCode %><br>
    <%= f.text_field :isinCode %>
  </div>
  <div class="field">
    <%= f.label :cnpj %><br>
    <%= f.text_field :cnpj %>
  </div>
  <div class="field">
    <%= f.label :exclusive %><br>
    <%= f.check_box :exclusive %>
  </div>
  <div class="field">
    <%= f.label :nqPeerGroupName %><br>
    <%= f.text_field :nqPeerGroupName %>
  </div>
  <div class="field">
    <%= f.label :niPeerGroupName %><br>
    <%= f.text_field :niPeerGroupName %>
  </div>
  <div class="field">
    <%= f.label :cvmClass %><br>
    <%= f.text_field :cvmClass %>
  </div>
  <div class="field">
    <%= f.label :anbimaClass %><br>
    <%= f.text_field :anbimaClass %>
  </div>
  <div class="field">
    <%= f.label :adminFee %><br>
    <%= f.text_field :adminFee %>
  </div>
  <div class="field">
    <%= f.label :performanceFeeDescription %><br>
    <%= f.text_area :performanceFeeDescription %>
  </div>
  <div class="field">
    <%= f.label :isIgi %><br>
    <%= f.check_box :isIgi %>
  </div>
  <div class="field">
    <%= f.label :isIgiExotic %><br>
    <%= f.check_box :isIgiExotic %>
  </div>
  <div class="field">
    <%= f.label :hasRestriction %><br>
    <%= f.check_box :hasRestriction %>
  </div>
  <div class="field">
    <%= f.label :targetClientList %><br>
    <%= f.text_field :targetClientList %>
  </div>
  <div class="field">
    <%= f.label :minimumInvestmentAmount %><br>
    <%= f.text_field :minimumInvestmentAmount %>
  </div>
  <div class="field">
    <%= f.label :vehicleType %><br>
    <%= f.text_field :vehicleType %>
  </div>
  <div class="field">
    <%= f.label :redemptionPaymentPeriod %><br>
    <%= f.text_field :redemptionPaymentPeriod %>
  </div>
  <div class="field">
    <%= f.label :redemptionConversionPeriod %><br>
    <%= f.text_field :redemptionConversionPeriod %>
  </div>
  <div class="field">
    <%= f.label :totalShareHolders %><br>
    <%= f.number_field :totalShareHolders %>
  </div>
  

  <dib class="field">
  <%= f.label :manager_id %><br>
    <%= f.collection_select(:manager_id, Manager.all, :id, :name, prompt: true)%>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

db2/app/views/funds/edit.html.erb
<h1>Editing Fund</h1>

<%= render 'form' %>

<%= link_to 'Show', @fund %> |
<%= link_to 'Back', funds_path %>

db2/app/views/funds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Funds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Shortname</th>
      <th>Isincode</th>
      <th>Cnpj</th>
      <th>Exclusive</th>
      <th>Nqpeergroupname</th>
      <th>Nipeergroupname</th>
      <th>Cvmclass</th>
      <th>Anbimaclass</th>
      <th>Adminfee</th>
      <th>Performancefeedescription</th>
      <th>Isigi</th>
      <th>Isigiexotic</th>
      <th>Hasrestriction</th>
      <th>Targetclientlist</th>
      <th>Minimuminvestmentamount</th>
      <th>Vehicletype</th>
      <th>Redemptionpaymentperiod</th>
      <th>Redemptionconversionperiod</th>
      <th>Totalshareholders</th>
       <th>Manager</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @funds.each do |fund| %>
      <tr>
        <td><%= fund.name %></td>
        <td><%= fund.shortName %></td>
        <td><%= fund.isinCode %></td>
        <td><%= fund.cnpj %></td>
        <td><%= fund.exclusive %></td>
        <td><%= fund.nqPeerGroupName %></td>
        <td><%= fund.niPeerGroupName %></td>
        <td><%= fund.cvmClass %></td>
        <td><%= fund.anbimaClass %></td>
        <td><%= fund.adminFee %></td>
        <td><%= fund.performanceFeeDescription %></td>
        <td><%= fund.isIgi %></td>
        <td><%= fund.isIgiExotic %></td>
        <td><%= fund.hasRestriction %></td>
        <td><%= fund.targetClientList %></td>
        <td><%= fund.minimumInvestmentAmount %></td>
        <td><%= fund.vehicleType %></td>
        <td><%= fund.redemptionPaymentPeriod %></td>
        <td><%= fund.redemptionConversionPeriod %></td>
        <td><%= fund.totalShareHolders %></td>
        <td><%= fund.manager.name %></td>
        <td><%= link_to 'Show', fund %></td>
        <td><%= link_to 'Edit', edit_fund_path(fund) %></td>
        <td><%= link_to 'Destroy', fund, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fund', new_fund_path %>

db2/app/views/funds/new.html.erb
<h1>New Fund</h1>

<%= render 'form' %>

<%= link_to 'Back', funds_path %>

db2/app/views/funds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fund.name %>
</p>

<p>
  <strong>Shortname:</strong>
  <%= @fund.shortName %>
</p>

<p>
  <strong>Isincode:</strong>
  <%= @fund.isinCode %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @fund.cnpj %>
</p>

<p>
  <strong>Exclusive:</strong>
  <%= @fund.exclusive %>
</p>

<p>
  <strong>Nqpeergroupname:</strong>
  <%= @fund.nqPeerGroupName %>
</p>

<p>
  <strong>Nipeergroupname:</strong>
  <%= @fund.niPeerGroupName %>
</p>

<p>
  <strong>Cvmclass:</strong>
  <%= @fund.cvmClass %>
</p>

<p>
  <strong>Anbimaclass:</strong>
  <%= @fund.anbimaClass %>
</p>

<p>
  <strong>Adminfee:</strong>
  <%= @fund.adminFee %>
</p>

<p>
  <strong>Performancefeedescription:</strong>
  <%= @fund.performanceFeeDescription %>
</p>

<p>
  <strong>Isigi:</strong>
  <%= @fund.isIgi %>
</p>

<p>
  <strong>Isigiexotic:</strong>
  <%= @fund.isIgiExotic %>
</p>

<p>
  <strong>Hasrestriction:</strong>
  <%= @fund.hasRestriction %>
</p>

<p>
  <strong>Targetclientlist:</strong>
  <%= @fund.targetClientList %>
</p>

<p>
  <strong>Minimuminvestmentamount:</strong>
  <%= @fund.minimumInvestmentAmount %>
</p>

<p>
  <strong>Vehicletype:</strong>
  <%= @fund.vehicleType %>
</p>

<p>
  <strong>Redemptionpaymentperiod:</strong>
  <%= @fund.redemptionPaymentPeriod %>
</p>

<p>
  <strong>Redemptionconversionperiod:</strong>
  <%= @fund.redemptionConversionPeriod %>
</p>

<p>
  <strong>Totalshareholders:</strong>
  <%= @fund.totalShareHolders %>
</p>
<p>
  <strong>Manager:</strong>
  <%= @fund.manager.name %>
</p>

<%= link_to 'Edit', edit_fund_path(@fund) %> |
<%= link_to 'Back', funds_path %>